// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuhamcbuvecwvxwdrasw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1aGFtY2J1dmVjd3Z4d2RyYXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODA0MTksImV4cCI6MjA1ODg1NjQxOX0.56WVom8TV90lmWJOk2_tKFB89DaF8PafiblogegOyyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);